

class RandomGenerator{
	constructor(minVal,maxVal){
		 this.minVal=minVal;
		 this.maxVal=maxVal;
		 this.randomNum=null;
		 
		//takes in the minimum and maximum values
		if(minVal===undefined){
			this.minVal=1;
		}
		if(maxVal===undefined){
			this.maxVal=10;
		}
		//if they are not defined, it sets the minimum to 1, and the max to 10
		//makes storage for the random number
		this.range={
			min: this.minVal,
			max: this.maxVal
		}
	}
	generate(){
		this.randomNum=Math.floor((Math.random()*this.maxVal)+this.minVal);
		//make a random value between the minimum and maximum values
		//and store the number into the storage from the constructor
	}
	getRange(){
		
		return this.range;
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		//returns a basic object literal
	}
	getNum(){
		return this.randomNum;
		//return the random number that was generated by generate()
	}
}